### ISSUE TITLE
Unable to launch any games with plugin

### ISSUE THREAD

**Issue by Posiris** [mupen64plus/mupen64plus-video-glide64mk2#114]
I'm running Elementary OS 5.1.7 and updated Mupen64Plus to 2.5.9.  I've checked and the .so file is in the appropriate folder.  Here is the log file when trying to launch a game from terminal:

mupen64plus --resolution 640x480 --fullscreen --gfx mupen64plus-video-glide64mk2  ~/Games/N64/Quake.n64
 __  __                         __   _  _   ____  _             
|  \/  |_   _ _ __   ___ _ __  / /_ | || | |  _ \| |_   _ ___ 
| |\/| | | | | '_ \ / _ \ '_ \| '_ \| || |_| |_) | | | | / __|  
| |  | | |_| | |_) |  __/ | | | (_) |__   _|  __/| | |_| \__ \  
|_|  |_|\__,_| .__/ \___|_| |_|\___/   |_| |_|   |_|\__,_|___/  
             |_|         https://mupen64plus.org/               
Mupen64Plus Console User-Interface Version 2.5.9

UI-Console: attached to core library 'Mupen64Plus Core' version 2.5.9
UI-Console:             Includes support for Dynamic Recompiler.
Core: Using full mem base
Core: Goodname: Quake 64 (U) [!]
Core: Name: Quake               
Core: MD5: 097605021951024C3ECB2D502C0C2A9F
Core: CRC: 9F5BF79C D2FE08A0
Core: Imagetype: .v64 (byteswapped)
Core: Rom size: 12582912 bytes (or 12 Mb or 96 Megabits)
Core: Version: 1448
Core: Manufacturer: Nintendo
Core: Country: USA
UI-Console Status: Cheat codes disabled.
UI-Console Error: dlopen('/usr/local/lib/mupen64plus/mupen64plus-video-glide64mk2.so') failed: libboost_filesystem.so.1.65.0: cannot open shared object file: No such file or directory
UI-Console Error: Specified Video plugin not found: mupen64plus-video-glide64mk2
Core Status: Rom closed.

**Comment by Narann** [comment]
This line states a lib is missing:

```
UI-Console Error: dlopen('/usr/local/lib/mupen64plus/mupen64plus-video-glide64mk2.so') failed: libboost_filesystem.so.1.65.0: cannot open shared object file: No such file or directory
```

Install `libboost_filesystem.so.1.65.0` and retry.

**Comment by Posiris** [comment]
1.65.1 is already installed.  Is there a way that I can direct mupen64plus to the file?
