### ISSUE TITLE
Use `GL_NUM_EXTENSIONS` and `glGetStringi` to check OpenGL extensions

### ISSUE THREAD

**Issue by jgcodes2020** [mupen64plus/mupen64plus-video-glide64mk2#126]
According to official documentation, `glGetString(GL_EXTENSIONS)` will return `NULL`. ([link](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glGetString.xhtml))

The officially supported method goes something like:
```c++
int numExtensions = 0;
glGetIntegerv(GL_NUM_EXTENSIONS, &numExtensions);
for (int i = 0; i < numExtensions; i++) {
  const char* ext = (const char*) glGetStringi(GL_EXTENSIONS, i);
  // do something with ext
}
```

A similar issue for Rice has been posted here: https://github.com/mupen64plus/mupen64plus-video-rice/issues/109

**Comment by richard42** [comment]
I believe that this documentation is referring to the Core (OpenGL 3.0) profile, whereas these video plugins are so old that they are still using the Compatibility (OpenGL 1.2) profile. So the current behavior is correct.
