### ISSUE TITLE
Current glide64mk2 is incompatible with RMG. Can someone make a new build that works? Needs an update.

### ISSUE THREAD

**Issue by BruceShankleIV** [mupen64plus/mupen64plus-video-glide64mk2#127]
I want to use glide64mk2 with Rosalie's Mupen GUI, but the plugin never shows up in the options menu. I asked about it and was told that the plugin is an old version and a new one needs to be made for it to work, and that I should bring it up here as an issue. Hopefully this is the right place.

However, I did try to force the plugin to load by editing the mupen64plus.cfg file to use glide64mk2 by default, and I got the error message attached to this message. Maybe that can help somebody find out how to make it work. I also understand that this is an old plugin that is obsoleted by GLideN64 for modern use, however I would like to be able to use this plugin so that I can play some older romhacks that relied on inaccuracies with older gfx plugins in order to work using RMG, since I prefer it over other emu's.

![cachedImage](https://github.com/mupen64plus/mupen64plus-video-glide64mk2/assets/159595828/1127925a-c923-4325-923c-65997d00e47c)

**Comment by Jj0YzL5nvJ** [comment]
The build in my repository is [more recent... you can try it](https://github.com/Jj0YzL5nvJ/mupen64plus-video-glide64mk2/releases/tag/nightly-build). Omit rewriting the already existing dependencies in RMG.

I'm planning a CI/CD update for this and other repositories, but I don't have time right now.

**Comment by BruceShankleIV** [comment]
Thanks for replying, I tried it and got the error attached to this message. I tried with the dll files from mupen64plus-video-glide64mk2-msvc-x64-gd900f21. I tried adding the SDL file to the main emulator too, that still didn't change it though. But please let me know when you update it in the future though, I would love to be able to use this plugin with RMG.
![Capture](https://github.com/mupen64plus/mupen64plus-video-glide64mk2/assets/159595828/71278ef7-2109-4582-9316-357411073a93)

**Comment by Jj0YzL5nvJ** [comment]
A clarification, no plugin directly maintained by mupen64plus has a GUI. However, the issue with `osal` was genuine (mupen64plus/mupen64plus-core#1040).

Preferably you should use the MSYS2 x64 version for RMG. The MSVC version is more glitchy in general. Glide64* only "worked fine" on x86 to begin with.
The `glew32.dll` and `libboost_filesystem-mt.dll` files must be in the same path as `RMG.exe`, `Glide64mk2.ini` must be in the `Data` folder and `mupen64plus-video-glide64mk2.dll` must be in the `Plugin\GFX` folder.
The other dependencies already exist in RMG so there is no need to replace them.

If you want to change the configuration of glide64mk2 for RMG, you will have to directly edit the file mupen64plus.cfg (`notepad "%APPDATA%\Mupen64Plus\mupen64plus.cfg"`)

Note: The only reason I can think of to continue using glide64* related plugins at this date, isn't having OpenGL 3.3 support.

**Comment by BruceShankleIV** [comment]
Thanks man, that worked perfectly! And the reason I wanted to use Glide64 was for romhacks that don't work with GLideN64, the model geometry completely breaks with GLideN64 and other more accurate plugins. But now that Glide64mk2 works, they can be played now. For an example, look at the screenshots I attached to this message. Very much appreciate your help with this 👍
 
![izou_zelda_patch_one-000](https://github.com/mupen64plus/mupen64plus-video-glide64mk2/assets/159595828/9c91a815-b67d-4858-aab7-7a86d2f91972)
![izou_zelda_patch_one-002](https://github.com/mupen64plus/mupen64plus-video-glide64mk2/assets/159595828/e4acdc00-e78e-4714-80aa-6cdb395e492b)
