### ISSUE TITLE
Hotkeys not working on Linux

### ISSUE THREAD

**Issue by vtj** [mupen64plus/mupen64plus-video-glide64mk2#47]
None of the hotkeys mentioned [here](https://github.com/mupen64plus/mupen64plus-video-glide64mk2/blob/master/src/Glide64/Help/Glide64%20Readme.html#Hotkeys) seem to be working on Linux. Neither the emulator window nor console is showing any response after pressing any of the aformentioned keybinds. I'm using the latest version compiled according to the instructions [here](https://code.google.com/p/mupen64plus/wiki/CompilingFromGit).

EDIT by Naran: Please format your message. :)

**Comment by Narann** [comment]
I think the html page you point is deprecated in favor of [this one](https://code.google.com/p/mupen64plus/wiki/KeyboardSetup).

**Comment by richard42** [comment]
I think there is currently no support in Mupen64Plus for a video plugin to get keypress events and react to them.  This glide readme file is a left-over from before we ported this to Mupen64Plus.
