### ISSUE TITLE
Different colors in kirby arms

### ISSUE THREAD

**Issue by sergiobenrocha2** [mupen64plus/mupen64plus-video-glide64mk2#54]
Kirby has different colors in his arms, in some scenes. Using rsp-hle or cxd4. Ubuntu 14.04, 64 bits.

![kirby64-002](https://cloud.githubusercontent.com/assets/5431285/7258668/66bde0d4-e834-11e4-833f-5a8ebf33a949.png)

**Comment by richard42** [comment]
yeah I saw this as well.  it affects several different games in my regression test.  Yesterday I tried to track down which commit caused this problem, but for some reason I was unable to reproduce when running directly from the command line.  I'll try again today.

**Comment by richard42** [comment]
ok, I found it. this regression was due to pull request #51 - commit f28bde1dc517c949fcdac8ac1ad5fe06ae586ac3

**Comment by richard42** [comment]
okay, the offending commit has been reverted

**Comment by conchurnavid** [comment]
And now it crashes again... weird arms exchanged with a crash :-(

**Comment by Narann** [comment]
@conchurnavid Could you open an issue with a step by step reproduction case. @richard42 imply it didn't crash on his side.
