### ISSUE TITLE
Paper Mario Star spirit text missing

### ISSUE THREAD

**Issue by fzurita** [mupen64plus/mupen64plus-video-glide64mk2#77]
When star spirits talk in Paper Mario, their text doesn't show up. The text does seem to have some effect applied to it that may use noise emulation.

**Comment by fzurita** [comment]
This turned out to be a configuration issue.

**Comment by dguyonvarch** [comment]
Hello,
same problem :( 
What is the expected configuration to make texts appear ?

**Comment by fzurita** [comment]
If I remember correctly, you have to enable noise for that game.

See here:
https://github.com/mupen64plus-ae/mupen64plus-ae/blob/master/app/src/main/assets/mupen64plus_data/Glide64mk2.ini

**Comment by dguyonvarch** [comment]
Hum 🤔 this configuration is different that one i use (see https://github.com/mupen64plus/mupen64plus-video-glide64mk2/blob/master/data/Glide64mk2.ini#L951)
The only setting missing compared to this one is `stipple_mode` (3DFX Dithered alpha emulation mode). 
I will test this soon 😉 
thks

**Comment by dguyonvarch** [comment]
That's it ! 
The default value for `stipple_mode` is 2. So override this setting by 0 for Paper Mario 64 makes the Star spirit texts appear.
To add context, its runs on a rpi4. Hoping it will be useful for someone else 🚀
