### ISSUE TITLE
Change __builtin_ia32_storeups() use in favor of _mm_storeu_ps()

### ISSUE THREAD

**Issue by Narann** [mupen64plus/mupen64plus-video-glide64mk2#87]
Following #86, we realize latest version of clang doesn't support `__builtin_ia32_storeups()` anymore and need to be replaced by `xmmintrin.h` intrinsic `_mm_storeu_ps()`. Example [here](https://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20160530/360722.html).

Looks easy. Someone want to give a try?

**Comment by bsmiles32** [comment]
See PR  #88
